// Arborele de decizii — Partea II (litigii premergătoare încheierii contractului)
// Sursa: „Ghid practic — Inițiere în litigiile din materia achizițiilor publice”, actualizat la 27.09.2026.
// lvl: 0 procedura de atribuire · 1 CNSC / tribunal · 2 curtea de apel · 3 căi extraordinare
// tr: contract (față) · cnsc (mijloc) · jud (spate); dz = decalaj pe adâncime; risc = coboară sub nivel

export const LEVELS = [
  { id: 0, name: 'Procedura de atribuire', short: 'Procedura' },
  { id: 1, name: 'Contestația · CNSC sau tribunal', short: 'Prima treaptă' },
  { id: 2, name: 'Curtea de apel', short: 'Curtea de apel' },
  { id: 3, name: 'Căi extraordinare de atac', short: 'Căi extraordinare' },
];

export const TRACKS = {
  contract: { z: 7.5, name: 'Încheierea contractului' },
  cnsc: { z: 0, name: 'Calea CNSC' },
  jud: { z: -8, name: 'Calea judiciară' },
};

export const ROLES = {
  ofertant: 'Ofertantul care atacă',
  castigator: 'Câștigătorul',
  ac: 'Autoritatea contractantă',
};

export const TYPES = {
  moment: 'Etapă',
  decizie: 'Punct de decizie',
  remediu: 'Cerere / cale de atac',
  solutie: 'Soluție',
  risc: 'Capcană',
  link: 'Trimitere',
};

const ALL = ['ofertant', 'castigator', 'ac'];

export const NODES = [
  // ───────── Procedura de atribuire (nivel 0)
  {
    id: 'p_anunt', type: 'moment', lvl: 0, tr: 'cnsc', col: 0, roles: ALL,
    t: 'Publicarea anunțului de participare', s: 'Anunțul de participare',
    sum: 'Ziua 0 a procedurii. Anunțul și documentația de atribuire devin accesibile oricui, direct, complet și gratuit, prin SEAP.',
    f: [
      ['Ce urmărești', 'Clarificările publicate în SEAP: AC răspunde cu cel puțin 10 zile înainte de termen (art. 160–161 L98). Data-limită de depunere este la cel puțin 35 de zile de la transmiterea anunțului (art. 74 L98).'],
      ['Accesul', 'Documentele achiziției sunt accesibile din ziua publicării (art. 150 L98). Identitatea celui care cere clarificări rămâne protejată.'],
    ],
    ref: ['I.2.3', 'II.2.3'], art: 'art. 72, 74, 150 L98',
  },
  {
    id: 'd_doc', type: 'decizie', lvl: 0, tr: 'cnsc', col: 1.5, roles: ['ofertant'],
    t: 'Documentația pare restrictivă sau neclară?', s: 'Atac documentația?',
    sum: 'Operatorul economic interesat decide dacă atacă documentația înainte de data-limită de depunere a ofertelor. Exemple: cerințe de calificare restrictive, specificații tehnice sau factori de evaluare discriminatori, documentație neclară.',
    f: [
      ['Momentul', 'Termenul curge de la publicarea documentației în SEAP. Un client care consideră o cerință restrictivă trebuie să o conteste imediat.'],
      ['Calitatea', 'Contestatorul acționează ca operator economic interesat, pentru că nu a depus încă ofertă.'],
      ['Alegerea căii', 'Calea CNSC: fără taxă, cu cauțiune. Calea judiciară: taxă de timbru de 2% din valoarea estimată. Ghidul recomandă calea CNSC.'],
    ],
    ref: ['II.2', 'II.2.2', 'II.1.2'], art: 'art. 8 alin. 2 L101',
  },
  {
    id: 'r_tardiv', type: 'risc', lvl: 0, tr: 'cnsc', col: 2.3, dz: 2.6, roles: ['ofertant'],
    t: 'Critici la documentație invocate abia la rezultat', s: 'Critici tardive',
    sum: 'Sunt respinse ca tardive: termenul pentru criticile privind documentația a curs de la publicarea ei.',
    ref: ['II.2.2'], art: 'art. 8 L101',
  },
  {
    id: 'p_depunere', type: 'moment', lvl: 0, tr: 'cnsc', col: 3, roles: ALL,
    t: 'Data-limită de depunere a ofertelor', s: 'Depunerea ofertelor',
    sum: 'Închide fereastra de contestare a documentației. Ofertele concurenților rămân inaccesibile până la publicarea raportului procedurii.',
    f: [
      ['Plafonul cauțiunii se schimbă', 'Înainte de depunere: max. 35.000 lei sub prag și 220.000 lei peste prag. După depunere: max. 88.000 lei, respectiv 2.000.000 lei.'],
    ],
    ref: ['I.2.3', 'II.2.4'], art: 'art. 74 L98; art. 61¹ L101',
  },
  {
    id: 'p_eval', type: 'moment', lvl: 0, tr: 'cnsc', col: 4, roles: ALL,
    t: 'Evaluarea ofertelor', s: 'Evaluarea',
    sum: 'De regulă: calificare (DUAE), apoi propunerea tehnică, apoi propunerea financiară, inclusiv prețul aparent neobișnuit de scăzut. Comisia poate cere clarificări pe tot parcursul. Documentele justificative ale DUAE se cer numai ofertantului clasat pe primul loc.',
    f: [
      ['Acte atacabile', 'Și actele intermediare pot fi atacate, de exemplu o solicitare de clarificări.'],
      ['Accesul', 'Nimic din ofertele concurenților, până la publicarea raportului (art. 65 alin. 2 L98).'],
    ],
    ref: ['I.2.3'], art: 'art. 193, 196, 209, 210 L98',
  },
  {
    id: 'p_rezultat', type: 'moment', lvl: 0, tr: 'cnsc', col: 5, roles: ALL,
    t: 'Raportul procedurii și comunicarea rezultatului', s: 'Comunicarea rezultatului',
    sum: 'Raportul se întocmește în max. 60 de zile lucrătoare de la termen, iar rezultatul se comunică în max. 3 zile. Raportul se publică în SEAP în aceeași zi.',
    f: [
      ['Ce primești', 'Motivele respingerii ofertei proprii, caracteristicile și avantajele relative ale ofertei câștigătoare, numele câștigătorului (art. 215 L98).'],
      ['Ce pornește', 'Termenul de contestare (10 sau 7 zile) și termenul de așteptare (11 sau 8 zile). Termenul de așteptare e mai lung, deci o contestație depusă în termen ajunge înainte ca AC să poată semna.'],
    ],
    ref: ['I.2.3', 'II.2.3', 'II.7.1'], art: 'art. 214–215 L98',
  },
  {
    id: 'a_acces', type: 'remediu', lvl: 0, tr: 'cnsc', col: 5.6, dz: 3.4, roles: ['ofertant', 'castigator'],
    t: 'Cerere de acces la dosarul achiziției', s: 'Acces la dosar',
    sum: 'După comunicarea rezultatului, orice ofertant poate cere acces la dosarul achiziției. AC trebuie să-l acorde în cel mult o zi lucrătoare.',
    f: [
      ['Termenul', 'Cererea se face imediat după comunicarea rezultatului; AC răspunde în max. 1 zi lucrătoare (art. 217 alin. 6 L98).'],
      ['La ce ai acces', 'Raportul procedurii, informațiile din afara propunerilor tehnice și financiare și părțile din propunerile tehnice și din justificările de preț nedeclarate și nedovedite confidențiale.'],
      ['Confidențialitatea', 'Sunt protejate doar informațiile indicate și dovedite de ofertant; o declarație generală de confidențialitate nu ajunge (art. 57 L98). Refuzul AC de a comunica informațiile este un act atacabil (CJUE, Klaipėdos, C-927/19).'],
    ],
    warn: 'Accesul refuzat sau întârziat nu oprește termenul de contestare.',
    ref: ['II.2.3'], art: 'art. 57, 217 L98',
  },
  {
    id: 'd_rez', type: 'decizie', lvl: 0, tr: 'cnsc', col: 6.5, roles: ['ofertant'],
    t: 'Oferta ta nu a câștigat. Contești rezultatul?', s: 'Atac rezultatul?',
    sum: 'Ofertantul necâștigător decide dacă atacă raportul procedurii. Strategia uzuală: contestă rezultatul și critică ofertele tuturor operatorilor clasați înaintea sa.',
    f: [
      ['Interesul', 'Dacă nu îi contestă pe toți cei clasați înainte, nu își poate justifica interesul. De exemplu, locul III îi contestă pe ofertanții de pe locurile I și II.'],
      ['Ofertantul exclus', 'Interesul există cât timp nu a fost exclus definitiv. Cel exclus care atacă simultan excluderea și atribuirea poate cere și excluderea ofertei câștigătoare (CJUE, Archus, C-131/16).'],
      ['Alegerea căii', 'La o valoare estimată de 700.000.000 lei, cauțiunea la CNSC este plafonată la 2.000.000 lei și se recuperează de regulă; taxa de timbru la tribunal ar fi de 14.000.000 lei.'],
    ],
    ref: ['II.1.1', 'II.1.2', 'II.1.3'], art: 'art. 3 alin. 1 lit. f, alin. 3 L101',
  },
  {
    id: 'd_castig', type: 'decizie', lvl: 0, tr: 'cnsc', col: 6.5, dz: -3.6, roles: ['castigator'],
    t: 'Oferta ta a câștigat. Cum aperi rezultatul?', s: 'Apăr rezultatul?',
    sum: 'Câștigătorul așteaptă contestațiile concurenților și formulează cereri de intervenție prin care apără decizia de atribuire și, eventual, critică ofertele contestatorilor.',
    f: [
      ['Ce faci', 'Monitorizezi SEAP zilnic după comunicarea rezultatului. AC trebuie să publice contestația în 1 zi de la primire, iar termenul de intervenție curge de la această publicare.'],
    ],
    ref: ['II.1.3', 'II.3.2'], art: 'art. 16 alin. 2, art. 17 alin. 3 L101',
  },

  // ───────── Încheierea contractului (pista din față)
  {
    id: 'k_asteptare', type: 'moment', lvl: 0, tr: 'contract', col: 5.5, roles: ALL,
    t: 'Termenul de așteptare', s: 'Termenul de așteptare',
    sum: 'AC nu poate semna contractul înainte de expirarea lui.',
    f: [
      ['Durata', '11 zile peste pragul UE și 8 zile sub prag, de la ziua următoare trimiterii deciziei de atribuire; +5 zile dacă decizia se comunică pe alte căi decât cele electronice (art. 59 alin. 2).'],
      ['Când e facultativ', 'Când nu era obligatorie publicarea unui anunț de participare, când a existat un singur ofertant și nu mai sunt alți operatori implicați, sau la contractele subsecvente unui acord-cadru ori unui sistem dinamic de achiziții (art. 59 alin. 3).'],
      ['Efectul contestației', 'Contestația nu prelungește termenul de așteptare, dar blochează semnarea (art. 59 alin. 4).'],
    ],
    ref: ['II.7.1'], art: 'art. 59 L101',
  },
  {
    id: 'k_f1', type: 'risc', lvl: 0, tr: 'contract', col: 5.5, dz: 2.6, roles: ['ac', 'castigator'],
    t: 'Semnare înainte de expirarea termenului de așteptare', s: 'Semnare prematură',
    sum: 'Interdicție (prima „fereastră”). Sancțiunea este nulitatea absolută sau sancțiunile alternative.',
    ref: ['II.7.2'], art: 'art. 58 alin. 6 L101',
  },
  {
    id: 'k_liber', type: 'solutie', lvl: 0, tr: 'contract', col: 7.3, roles: ['ac', 'castigator'], outcome: 'neutral',
    t: 'Nicio contestație: AC poate semna', s: 'Semnare permisă',
    sum: 'Dacă nu s-a depus contestație, AC are dreptul să semneze contractul după expirarea termenului de așteptare.',
    f: [
      ['Termen facultativ', 'AC poate semna imediat; o contestație ulterioară se soluționează totuși (art. 9 alin. 5 teza a II-a).'],
      ['Contestație după semnare', 'CNSC soluționează oricum contestația. Rezultatul poate fundamenta ulterior acțiunea în nulitate sau în despăgubiri (Partea III).'],
    ],
    ref: ['II.7.3', 'II.7.4'], art: 'art. 59 alin. 1; art. 9 alin. 5 L101',
  },
  {
    id: 'k_blocaj', type: 'moment', lvl: 0, tr: 'contract', col: 8.3, roles: ALL,
    t: 'Contestație nesoluționată: AC nu semnează', s: 'Semnare blocată',
    sum: 'A doua „fereastră”. AC așteaptă soluția CNSC sau a tribunalului. Contractul încheiat înainte de primirea deciziei asupra contestației este lovit de nulitate absolută.',
    f: [
      ['Contestații multiple', 'Blocajul durează până la soluționarea tuturor contestațiilor care vizează rezultatul, care sunt conexate (art. 17 alin. 2).'],
      ['Pronunțare sau primire', 'Art. 9 alin. 4 leagă obligația de a semna de pronunțarea soluției de menținere, iar art. 58 alin. 2 lit. e sancționează semnarea înainte de primirea deciziei. Prudent, AC semnează după ce a primit decizia.'],
    ],
    ref: ['II.7.2', 'II.7.5'], art: 'art. 58 alin. 2 lit. e L101',
  },
  {
    id: 'k_null', type: 'risc', lvl: 0, tr: 'contract', col: 8.3, dz: 2.6, roles: ['ac', 'castigator'],
    t: 'Contract semnat înainte de primirea deciziei', s: 'Nulitate absolută',
    sum: 'Contractul este lovit de nulitate absolută (art. 58 alin. 2 lit. e).',
    ref: ['II.7.2', 'II.7.3'], art: 'art. 58 alin. 2 lit. e L101',
  },
  {
    id: 'k_obligatie', type: 'moment', lvl: 0, tr: 'contract', col: 11, roles: ALL,
    t: 'Soluție de menținere: AC trebuie să semneze', s: 'Obligația de a semna',
    sum: 'A treia „fereastră”. După soluția de menținere a rezultatului, AC trebuie să semneze după expirarea termenului de așteptare, chiar dacă soluția este atacată cu plângere (calea CNSC) sau cu recurs (calea judiciară).',
    f: [
      ['Pentru câștigător', 'Poate invoca obligația legală a AC de a semna (art. 9 alin. 4 / art. 49 alin. 6).'],
      ['Pentru contestator', 'Singurul instrument care mai blochează semnarea este cererea de suspendare la curtea de apel, cu dovada unei pagube iminente (art. 33).'],
    ],
    warn: 'Întârzierea semnării după o soluție de menținere încalcă o obligație legală a AC. Contractul încheiat cu nerespectarea art. 9 alin. 4 este lovit de nulitate absolută.',
    ref: ['II.7.2', 'II.7.3', 'II.7.5'], art: 'art. 9 alin. 4–5; art. 49 alin. 6 L101',
  },
  {
    id: 'k_semnat', type: 'moment', lvl: 0, tr: 'contract', col: 12.6, roles: ALL,
    t: 'Contract încheiat', s: 'Contract încheiat',
    sum: 'După încheierea contractului, CNSC nu mai are competență. Litigiile privind executarea, nulitatea și despăgubirile sunt de competența instanțelor (Partea III).',
    f: [
      ['Clauza arbitrală', 'Părțile pot conveni ca litigiile privind interpretarea, încheierea, executarea, modificarea și încetarea contractului să fie soluționate prin arbitraj (art. 57). Verificați de la început dacă AC a inserat o clauză arbitrală.'],
    ],
    ref: ['II.1'], art: 'art. 57 L101',
  },
  {
    id: 'k_schimbare', type: 'moment', lvl: 0, tr: 'contract', col: 15.2, roles: ALL,
    t: 'Soluția se schimbă în calea de atac', s: 'Soluție răsturnată',
    sum: 'Contractul a fost semnat, iar calea de atac schimbă soluția. Consecințele depind de momentul semnării.',
    f: [
      ['Atenție', 'Nu în toate cazurile în care plângerea se admite, cu anularea actului atacat, ofertantul are la dispoziție remediul nulității contractului. Cazurile sunt prezentate la III.2.'],
    ],
    ref: ['II.7.4', 'II.4.7'], art: 'art. 34 alin. 3 L101',
  },
  {
    id: 'k_nul', type: 'risc', lvl: 0, tr: 'contract', col: 16.4, dz: 2.6, roles: ALL,
    t: 'Semnat înainte de comunicarea deciziei CNSC', s: 'Regimul nulității',
    sum: 'Dacă curtea de apel constată că actul era nelegal, se aplică regimul nulității din art. 58–61: nulitatea sau sancțiunile alternative (art. 34 alin. 3; III.2).',
    ref: ['II.7.4'], art: 'art. 34 alin. 3; art. 58–61 L101',
  },
  {
    id: 'k_desp', type: 'solutie', lvl: 0, tr: 'contract', col: 16.4, dz: -2.6, roles: ALL, outcome: 'neutral',
    t: 'Semnat corect, după menținere', s: 'Despăgubiri',
    sum: 'Legea nu prevede expres nulitatea contractului. Art. 58² reglementează despăgubirile: sunt suportate din bugetul AC, iar persoanele implicate răspund numai pentru culpă gravă constatată de instanță. Este o întrebare de practică de urmărit.',
    ref: ['II.7.4'], art: 'art. 58² L101',
  },
  {
    id: 'p3', type: 'link', lvl: 0, tr: 'contract', col: 17.8, roles: ALL,
    t: 'Partea III: litigii după încheierea contractului', s: 'Partea III',
    sum: 'Litigiile privind executarea contractului, nulitatea lui și prejudiciile cauzate în procedura de atribuire, inclusiv după anularea procedurii. Vor fi adăugate în versiunea următoare a hărții.',
    ref: ['III'],
  },

  // ───────── CNSC (nivel 1)
  {
    id: 'c_doc', type: 'remediu', lvl: 1, tr: 'cnsc', col: 2.2, roles: ['ofertant', 'ac'],
    t: 'Contestație împotriva documentației', s: 'Contestație · documentație',
    sum: 'Se formulează înainte de data-limită de depunere a ofertelor și critică anunțul de participare, fișa de date, caietul de sarcini sau clarificările publicate.',
    f: [
      ['Competența', 'CNSC, complet de trei membri, același pentru toate contestațiile din etapa de până la depunerea ofertelor (art. 17 alin. 1 lit. a).'],
      ['Termenul', '10 zile peste pragul UE și 7 zile sub prag, de la publicarea documentației în SEAP sau de la comunicare, dacă procedura se desfășoară fără publicare (art. 8 alin. 2).'],
      ['Cauțiunea', '2% din valoarea estimată, max. 35.000 lei sub prag și 220.000 lei peste prag, în cel mult 5 zile de la sesizarea CNSC (art. 61¹). Fără taxă de timbru.'],
      ['Conținutul', 'Art. 10: datele contestatorului, AC, obiectul contractului și anunțul din SEAP, actul atacat precis individualizat, ce se cere, motivarea în fapt și în drept, probele, semnătura.'],
      ['Depunerea', 'La CNSC și, în același termen, la AC, sub sancțiunea tardivității (art. 16 alin. 1). Recomandare: cu 1–2 zile înainte de expirarea termenului.'],
      ['Remedieri tipice', 'Modificarea sau eliminarea cerințelor, publicată în SEAP (art. 9 alin. 1; art. 26 alin. 3).'],
    ],
    warn: 'Contestația nu suspendă procedura: termenul de depunere a ofertelor continuă să curgă. Pentru a o opri e nevoie de o cerere de suspendare.',
    calc: { zile: [10, 7], de: 'Data publicării documentației în SEAP' },
    ref: ['II.2', 'II.2.2', 'II.2.4–II.2.6', 'II.6'], art: 'art. 8, 10, 16, 17, 61¹ L101',
  },
  {
    id: 'c_rez', type: 'remediu', lvl: 1, tr: 'cnsc', col: 6.5, roles: ALL,
    t: 'Contestație împotriva rezultatului', s: 'Contestație · rezultat',
    sum: 'Se formulează după comunicarea rezultatului și critică evaluarea calificării și a conformității tehnice, respingerea ofertei, punctajul sau desemnarea câștigătorului. Celelalte acte ale AC, de exemplu o solicitare de clarificări, se atacă tot de la luarea la cunoștință.',
    f: [
      ['Competența', 'CNSC; alt complet decât cel din etapa documentației, unic pentru toate contestațiile din această etapă, care se conexează (art. 17 alin. 1 lit. b).'],
      ['Termenul', '10 zile peste prag și 7 zile sub prag, de la luarea la cunoștință a actului, de regulă publicarea raportului în SEAP (art. 8 alin. 1). Potrivit CJUE (Alstom Transport, C-532/20), termenul nu curge înainte de comunicarea a cel puțin unui rezumat al motivelor pertinente.'],
      ['Cauțiunea', '2% din valoarea estimată, max. 88.000 lei sub prag și 2.000.000 lei peste prag, în 5 zile de la sesizare. La loturi: valoarea fiecărui lot contestat. La acordul-cadru: dublul valorii celui mai mare contract subsecvent.'],
      ['Conținutul', 'Elementele de la art. 10. Ce nu e invocat în termen nu mai poate fi adăugat: motivele și capetele de cerere noi sunt inadmisibile (art. 21 alin. 3), cu excepția criticilor care pot face obiectul unei noi contestații, de exemplu după obținerea accesului la acte care nu au fost accesibile în mod nejustificat. O nouă contestație presupune o nouă cauțiune.'],
      ['Depunerea', 'La CNSC și la AC, în același termen. Dovada cauțiunii trebuie să ajungă la CNSC în 5 zile.'],
      ['Efectul', 'Blochează semnarea contractului până la primirea deciziei (art. 58 alin. 2 lit. e). La procedurile pe loturi, efectele privesc doar loturile contestate (art. 9 alin. 6).'],
    ],
    calc: { zile: [10, 7], de: 'Data publicării raportului în SEAP' },
    ref: ['II.2', 'II.2.2', 'II.2.4–II.2.6', 'II.7'], art: 'art. 8, 10, 17, 21, 61¹ L101',
  },
  {
    id: 'r_caut', type: 'risc', lvl: 1, tr: 'cnsc', col: 3.6, dz: -2.4, roles: ['ofertant'],
    t: 'Cauțiune neconstituită în 5 zile', s: 'Fără cauțiune',
    sum: 'Contestația se respinge ca inadmisibilă (art. 61¹ alin. 1). Termenul curge de la sesizarea CNSC.',
    calc: { zile: [5], de: 'Data sesizării CNSC' },
    ref: ['II.2.4'], art: 'art. 61¹ alin. 1 L101',
  },
  {
    id: 'r_lipsuri', type: 'risc', lvl: 1, tr: 'cnsc', col: 5, dz: -2.4, roles: ['ofertant'],
    t: 'Lipsuri necompletate în 3 zile', s: 'Contestație anulată',
    sum: 'Lipsurile contestației se completează în 3 zile de la înștiințarea CNSC; altfel, contestația se anulează (art. 11 alin. 1).',
    ref: ['II.2.5'], art: 'art. 11 alin. 1 L101',
  },
  {
    id: 'r_dubla', type: 'risc', lvl: 1, tr: 'cnsc', col: 4.3, dz: -5, roles: ['ofertant'],
    t: 'Același act atacat și la CNSC, și la tribunal', s: 'Dublă contestare',
    sum: 'Se prezumă renunțarea la contestația de la CNSC (art. 4 alin. 6).',
    ref: ['II.1.2'], art: 'art. 4 alin. 6 L101',
  },
  {
    id: 'c_susp', type: 'remediu', lvl: 1, tr: 'cnsc', col: 4.3, dz: 3.4, roles: ['ofertant'],
    t: 'Cerere de suspendare la CNSC', s: 'Suspendare · CNSC',
    sum: 'Depunerea contestației nu suspendă procedura de atribuire (art. 59 alin. 4). CNSC poate suspenda, la cerere, procedura de atribuire sau orice decizie a AC.',
    f: [
      ['Când e utilă', 'Mai ales la contestațiile împotriva documentației: fără suspendare, termenul de depunere a ofertelor curge. La rezultat, AC oricum nu poate semna până la primirea deciziei CNSC.'],
      ['Termenul', 'De regulă odată cu contestația sau ulterior, până la soluționarea ei; se comunică simultan și AC. CNSC decide prin încheiere în 3 zile.'],
      ['Temeiuri', 'Cazuri bine justificate și prevenirea unei pagube iminente. CNSC pune în balanță toate interesele implicate, inclusiv interesul public.'],
      ['Calea de atac', 'Încheierea CNSC se atacă separat cu plângere, în 5 zile.'],
    ],
    ref: ['II.6'], art: 'art. 22–23; art. 59 alin. 4 L101',
  },
  {
    id: 'c_ac', type: 'moment', lvl: 1, tr: 'cnsc', col: 7.6, dz: -3, roles: ['ac'],
    t: 'Autoritatea contractantă primește contestația', s: 'Răspunsul AC',
    sum: 'AC publică contestația, poate adopta măsuri de remediere și transmite punctul de vedere.',
    f: [
      ['În 1 zi', 'Publică contestația în SEAP sau o comunică celorlalți participanți, dacă procedura se desfășoară fără publicare (art. 16 alin. 2).'],
      ['În 3 zile', 'Poate adopta măsuri de remediere, pe care le comunică în 1 zi contestatorului, celorlalți participanți și CNSC (art. 9 alin. 1).'],
      ['În 5 zile', 'Transmite punctul de vedere CNSC și contestatorului, iar CNSC și copia dosarului achiziției (art. 18).'],
    ],
    warn: 'Lipsa punctului de vedere o decade pe AC din dreptul de a propune probe și de a invoca excepții, altele decât cele de ordine publică (art. 18 alin. 3).',
    ref: ['II.2.7'], art: 'art. 9, 16, 18 L101',
  },
  {
    id: 'd_remediere', type: 'decizie', lvl: 1, tr: 'cnsc', col: 8.4, dz: -5.4, roles: ['ofertant'],
    t: 'AC a luat măsuri de remediere. Te satisfac?', s: 'Remedierea mă satisface?',
    sum: 'Dacă măsurile adoptate de AC îl satisfac, contestatorul poate renunța la contestație.',
    ref: ['II.2.7', 'II.1.1'], art: 'art. 9 alin. 3; art. 26 alin. 8 L101',
  },
  {
    id: 'i_interv', type: 'remediu', lvl: 1, tr: 'cnsc', col: 7.6, dz: 3.4, roles: ['castigator', 'ofertant'],
    t: 'Cerere de intervenție', s: 'Intervenție',
    sum: 'Prin ea, alt operator devine parte în procedura contestației. De regulă o formulează câștigătorul, pentru a apăra rezultatul și, eventual, a critica oferta contestatorului. Și contestatorii pot interveni împotriva contestațiilor celorlalți.',
    f: [
      ['Competența', 'Completul CNSC învestit cu contestația, care o soluționează împreună cu aceasta (art. 17).'],
      ['Termenul', '10 zile de la publicarea contestației în SEAP sau de la comunicarea ei, dacă procedura se desfășoară fără publicare (art. 17 alin. 3), nu de la data la care ai aflat din altă sursă.'],
      ['Costul', 'Fără cauțiune. Dacă intervenientul face ulterior plângere, depune o cauțiune de 50% din cea pentru contestație.'],
      ['Conținutul', 'Structura contestației, cu accent pe interesul intervenientului, argumentele împotriva contestației și eventualele critici privind evaluarea ofertei contestatorului.'],
      ['Depunerea', 'La CNSC și, în același termen, la AC și contestator (art. 17 alin. 4).'],
      ['Procedura', 'Concluzii scrise și, la cerere, dezbateri orale. Apărarea e separată de a AC; nu e ideal ca argumentele intervenientului să contrazică apărarea AC. CNSC admite sau respinge intervenția în principiu și o soluționează odată cu contestația.'],
    ],
    calc: { zile: [10], de: 'Data publicării contestației în SEAP' },
    ref: ['II.3'], art: 'art. 17, 21, 68 L101',
  },
  {
    id: 'r_interv', type: 'risc', lvl: 1, tr: 'cnsc', col: 8.4, dz: 5.6, roles: ['castigator'],
    t: 'Termenul de intervenție ratat', s: 'Intervenție ratată',
    sum: 'CNSC decide fără argumentele tale, iar apărarea rămâne doar în mâna AC. Poți face direct plângere, dar criticile sunt limitate: plângerea nu poate aduce motive noi față de cele dezbătute la CNSC (art. 30 alin. 2).',
    ref: ['II.3.2'], art: 'art. 17 alin. 3; art. 30 alin. 2 L101',
  },
  {
    id: 'c_proc', type: 'moment', lvl: 1, tr: 'cnsc', col: 9, roles: ALL,
    t: 'Procedura la CNSC', s: 'Procedura la CNSC',
    sum: 'Procedură scrisă: completul lucrează pe bază de înscrisuri, iar audierea are loc numai dacă o consideră necesară (art. 21).',
    f: [
      ['Contestatorul', 'Cere acces la dosarul CNSC (art. 19); răspunde prin concluzii scrise la punctul de vedere al AC și la intervenții, fără motive noi; își cere cheltuielile, cu cuantumul și dovezile, înainte de pronunțare (art. 26 alin. 9).'],
      ['CNSC', 'Conexează contestațiile; poate cere lămuriri cu termen de 3 zile, iar documentele nedepuse în termen nu mai pot fi depuse (art. 20); poate suspenda procedura de atribuire, la cerere; poate suspenda soluționarea contestației în cazurile art. 25.'],
      ['Accesul la dosar', 'Nu depinde de accesul obținut la AC. Documentele confidențiale trebuie marcate explicit și se consultă doar cu acordul scris al ofertantului (art. 19).'],
    ],
    ref: ['II.2.7', 'II.2.3'], art: 'art. 19–21, 25 L101',
  },
  {
    id: 'c_dec', type: 'moment', lvl: 1, tr: 'cnsc', col: 10.2, roles: ALL,
    t: 'Decizia CNSC', s: 'Decizia CNSC',
    sum: 'CNSC decide în 20 de zile de la primirea dosarului achiziției sau în 10 zile când o excepție împiedică analiza pe fond, cu o posibilă prelungire de 10 zile (art. 24). Excepțiile se analizează înaintea fondului.',
    f: [
      ['Adoptarea', 'Cu majoritate, fără abțineri; opinia separată se consemnează (art. 27 alin. 3).'],
      ['Comunicarea', 'Părților în 3 zile; pe site-ul CNSC în 5 zile, anonimizat; în SEAP, de AC, în 5 zile de la primire (art. 27).'],
      ['Efectele', 'Decizia este obligatorie pentru părți; contractul încheiat cu nerespectarea ei este lovit de nulitate absolută (art. 28 alin. 1 și 4).'],
      ['Limite', 'CNSC nu poate atribui contractul unui anumit operator, cu excepția situației în care acesta a fost desemnat de AC sau calitatea de câștigător rezultă din dosar (art. 26 alin. 10). Alte nelegalități observate din oficiu se sesizează ANAP și Curții de Conturi (art. 26 alin. 4).'],
    ],
    ref: ['II.2.8'], art: 'art. 24, 26–28 L101',
  },
  {
    id: 's_renunt', type: 'solutie', lvl: 1, tr: 'cnsc', col: 9.8, dz: -5.6, roles: ['ofertant'], outcome: 'neutral',
    t: 'Luarea act de renunțare', s: 'Renunțare',
    sum: 'Contestatorul poate renunța oricând în cursul soluționării (art. 26 alin. 8).',
    ref: ['II.2.8'], art: 'art. 26 alin. 8 L101',
  },
  {
    id: 's_exc', type: 'solutie', lvl: 1, tr: 'cnsc', col: 11.4, dz: -4.2, roles: ALL, outcome: 'mentinere',
    t: 'Respingere pe excepție', s: 'Respinsă pe excepție',
    sum: 'Contestația este tardivă, lipsită de interes, de obiect sau de calitate procesuală, ori formulată de un reprezentant cu calitate nedovedită. Fondul nu se mai analizează.',
    f: [['Pentru contestator', 'Interesul și respectarea termenului se documentează încă din contestație.']],
    ref: ['II.2.8'], art: 'art. 26 alin. 6 L101',
  },
  {
    id: 's_nef', type: 'solutie', lvl: 1, tr: 'cnsc', col: 11.4, dz: -1.4, roles: ALL, outcome: 'mentinere',
    t: 'Respingere ca nefondată', s: 'Respinsă ca nefondată',
    sum: 'Actul atacat este legal și temeinic. Rezultatul procedurii este menținut.',
    ref: ['II.2.8'], art: 'art. 26 alin. 6 L101',
  },
  {
    id: 's_anul', type: 'solutie', lvl: 1, tr: 'cnsc', col: 11.4, dz: 1.4, roles: ALL, outcome: 'admitere',
    t: 'Admitere: anulare sau obligare la remediere', s: 'Admisă · remediere',
    sum: 'Anularea totală sau parțială a actului, de exemplu a raportului procedurii, și/sau obligarea AC la măsuri de remediere indicate clar și precis. La reevaluare se indică ofertele, etapele și măsurile concrete (art. 26 alin. 10¹).',
    f: [
      ['Termenul de remediere', 'Nu poate fi mai scurt decât termenul de plângere (art. 26 alin. 5).'],
      ['Reevaluarea', 'AC poate verifica toate elementele tehnice și financiare ale ofertei apte să demonstreze admisibilitatea ei, dacă din probe nu rezultă verificarea lor anterioară (ÎCCJ, Decizia HP nr. 66/2018).'],
    ],
    ref: ['II.2.8'], art: 'art. 26 alin. 2 lit. a–b L101',
  },
  {
    id: 's_anproc', type: 'solutie', lvl: 1, tr: 'cnsc', col: 11.4, dz: 4.2, roles: ALL, outcome: 'admitere',
    t: 'Anularea procedurii', s: 'Procedură anulată',
    sum: 'CNSC anulează procedura de atribuire numai dacă remedierea nu este posibilă.',
    ref: ['II.2.8'], art: 'art. 26 alin. 2 lit. c, alin. 7 L101',
  },
  {
    id: 'd_pl', type: 'decizie', lvl: 1, tr: 'cnsc', col: 12.8, roles: ALL,
    t: 'Atacă cineva decizia CNSC?', s: 'Plângere?',
    sum: 'Decizia CNSC poate fi atacată cu plângere de AC și de orice persoană vătămată de măsurile dispuse, nu doar de cei care au participat la procedura în fața Consiliului (art. 29).',
    f: [
      ['Exemplu', 'Un membru al asocierii contestatoare care nu a semnat contestația poate formula direct plângere dacă contestația asociatului a fost respinsă.'],
      ['Intervenientul', 'Dacă CNSC admite contestația, intervenientul poate formula plângere în 10 zile, ca persoană vătămată de măsurile dispuse.'],
    ],
    ref: ['II.4.2', 'II.3.6'], art: 'art. 29 L101',
  },
  {
    id: 'a_exec', type: 'moment', lvl: 0, tr: 'cnsc', col: 12.8, roles: ['ac', 'ofertant', 'castigator'],
    t: 'AC execută soluția de admitere', s: 'AC execută soluția',
    sum: 'AC modifică documentația sau reevaluează ofertele, în limitele și în termenul stabilite de CNSC sau de instanță.',
    f: [
      ['Plângerea AC', 'Dacă AC atacă decizia de admitere, poate suspenda ea însăși executarea deciziei și/sau procedura până la soluționarea plângerii (art. 28 alin. 5).'],
    ],
    warn: 'AC nu semnează cu ofertantul inițial contrar deciziei: contractul ar fi lovit de nulitate absolută (art. 28 alin. 1 și 4).',
    ref: ['II.2.8', 'II.6.4', 'II.7.3'], art: 'art. 26 alin. 5; art. 28 L101',
  },
  {
    id: 'k_noua', type: 'moment', lvl: 0, tr: 'cnsc', col: 14.2, roles: ALL,
    t: 'Nouă decizie de atribuire după remediere', s: 'Nou rezultat',
    sum: 'Pornește un nou termen de așteptare, iar o nouă contestație este posibilă (art. 59 alin. 1).',
    ref: ['II.7.3'], art: 'art. 59 alin. 1 L101',
  },

  // ───────── Curtea de apel (nivel 2)
  {
    id: 'pl', type: 'remediu', lvl: 2, tr: 'cnsc', col: 12.8, roles: ALL,
    t: 'Plângere la curtea de apel', s: 'Plângere',
    sum: 'Calea de atac împotriva deciziei CNSC, pentru motive de nelegalitate și de netemeinicie (art. 29).',
    f: [
      ['Competența', 'Secția de contencios administrativ și fiscal a curții de apel de la sediul AC, complet specializat de 3 judecători. Pentru proiecte de infrastructură de transport de interes național: exclusiv Curtea de Apel București (art. 32).'],
      ['Termenul', '10 zile de la comunicarea deciziei CNSC, pentru părți, sau de la luarea la cunoștință, pentru ceilalți vătămați (art. 29).'],
      ['Costul', 'Scutită de taxă de timbru (art. 36¹). Cine a depus cauțiune la CNSC nu datorează alta. Orice alt petent depune 50% din cauțiunea pentru contestație. AC este scutită (art. 61¹).'],
      ['Conținutul', 'Elementele de la art. 10. Fără motive noi față de contestație (art. 30 alin. 2) și fără probe noi (art. 31 alin. 3).'],
      ['Depunerea', 'La curtea de apel, cu o copie la CNSC pentru transmiterea dosarului. O copie se comunică celorlalte părți în același termen de 10 zile, iar dovada se depune până la primul termen (art. 30–31).'],
    ],
    calc: { zile: [10], de: 'Data comunicării deciziei CNSC' },
    ref: ['II.4'], art: 'art. 29–32, 36¹, 61¹ L101',
  },
  {
    id: 'r_pl', type: 'risc', lvl: 2, tr: 'cnsc', col: 13.6, dz: -2.8, roles: ALL,
    t: 'Plângere necomunicată părților în termen', s: 'Plângere tardivă',
    sum: 'Plângerea necomunicată părților în 10 zile se respinge ca tardivă (art. 31 alin. 1). Pentru fiecare destinatar păstrezi: la e-mail, mesajul și confirmările Delivery Receipt și Read Receipt; prin poștă, nota de inventar, confirmarea de primire (sau extrasul Track&Trace) și factura.',
    ref: ['II.4.5'], art: 'art. 31 alin. 1 L101',
  },
  {
    id: 'pl_susp', type: 'remediu', lvl: 2, tr: 'cnsc', col: 13.6, dz: 3.4, roles: ['ofertant', 'castigator'],
    t: 'Cerere de suspendare la curtea de apel', s: 'Suspendare · curte',
    sum: 'Suspendarea procedurii de atribuire și/sau a executării contractului. După o decizie CNSC de menținere a rezultatului, este singurul instrument care blochează semnarea pe durata plângerii.',
    f: [
      ['Termenul', 'În cursul judecării plângerii.'],
      ['Temeiuri', 'Cazuri temeinic justificate și prevenirea unei pagube iminente, cu balanța tuturor intereselor (art. 33 alin. 1).'],
      ['Calea de atac', 'Încheierea curții de apel este definitivă (art. 33 alin. 13).'],
    ],
    warn: 'Art. 33 alin. 2–12 din textul consolidat (cauțiune pentru suspendare, cu plafoane între 35.000 și 880.000 lei) este marcat ca abrogat prin OUG 45/2018. Nu îl citați ca drept în vigoare.',
    ref: ['II.6', 'II.7.5'], art: 'art. 33 L101',
  },
  {
    id: 'pl_proc', type: 'moment', lvl: 2, tr: 'cnsc', col: 14.4, roles: ALL,
    t: 'Judecata plângerii', s: 'Judecata',
    sum: 'CNSC nu este parte în proces (art. 32 alin. 3).',
    f: [
      ['Întâmpinarea', 'Obligatorie, în 5 zile de la comunicarea plângerii de către petent, sub sancțiunea decăderii din excepții, altele decât cele de ordine publică (art. 31 alin. 2).'],
      ['Calendarul', 'Primul termen în max. 20 de zile de la înregistrare, următoarele la max. 15 zile, soluționarea în max. 45 de zile (art. 32 alin. 4–5).'],
      ['Hotărârea', 'Se redactează motivat în 7 zile; pronunțarea se poate amâna cu cel mult 5 zile (art. 35).'],
    ],
    calc: { zile: [5], de: 'Data comunicării plângerii (întâmpinare)' },
    ref: ['II.4.6'], art: 'art. 31–35 L101',
  },
  {
    id: 'pl_mod', type: 'solutie', lvl: 2, tr: 'cnsc', col: 15.6, dz: -3, roles: ALL, outcome: 'admitere',
    t: 'Admitere: decizia CNSC se modifică', s: 'Admisă · modificare',
    sum: 'Curtea modifică decizia CNSC: de exemplu anulează actul, obligă AC la remediere, elimină specificațiile discriminatorii sau anulează procedura.',
    ref: ['II.4.7'], art: 'art. 34 L101',
  },
  {
    id: 'pl_rejud', type: 'solutie', lvl: 2, tr: 'cnsc', col: 15.6, dz: 0, roles: ALL, outcome: 'neutral',
    t: 'Admitere: desființare și rejudecare', s: 'Admisă · rejudecare',
    sum: 'Când CNSC a rămas la o excepție sau a analizat doar o parte din motivele de contestație, curtea desființează decizia și reține cauza spre rejudecare. Fondul se judecă la un termen distinct.',
    ref: ['II.4.7'], art: 'art. 34 alin. 2 și 4 L101',
  },
  {
    id: 'pl_resp', type: 'solutie', lvl: 2, tr: 'cnsc', col: 15.6, dz: 3, roles: ALL, outcome: 'mentinere',
    t: 'Respingerea plângerii', s: 'Plângere respinsă',
    sum: 'Plângerea se respinge pe fond sau pe excepție.',
    ref: ['II.4.7'], art: 'art. 34 alin. 5 L101',
  },
  {
    id: 'pl_def', type: 'moment', lvl: 2, tr: 'cnsc', col: 16.9, roles: ALL,
    t: 'Hotărâre definitivă', s: 'Hotărâre definitivă',
    sum: 'Hotărârea curții de apel este definitivă. Poate fi atacată numai cu contestație în anulare sau cu revizuire.',
    f: [
      ['Contract deja încheiat', 'Dacă actul atacat era nelegal, dar contractul a fost deja încheiat, se aplică regulile privind nulitatea contractului, în măsura în care sunt aplicabile (art. 34 alin. 3; III.2).'],
    ],
    ref: ['II.4.7', 'II.5'], art: 'art. 34 alin. 3; art. 35 alin. 2 L101',
  },

  // ───────── Căi extraordinare (nivel 3)
  {
    id: 'x_ca', type: 'remediu', lvl: 3, tr: 'cnsc', col: 17.4, dz: -3.4, roles: ALL,
    t: 'Contestație în anulare', s: 'Contestație în anulare',
    sum: 'Se judecă de instanța care a pronunțat hotărârea atacată (art. 505 C.pr.civ.). L101 nu reglementează căile extraordinare; se aplică C.pr.civ. și Legea 554/2004, prin art. 68 L101.',
    f: [
      ['Termenul', '15 zile de la comunicarea hotărârii, dar nu mai târziu de un an de la rămânerea ei definitivă. Motivarea se depune în același termen, sub sancțiunea nulității (art. 506 C.pr.civ.).'],
      ['Temeiuri', 'De drept comun: contestatorul nu a fost legal citat și nici prezent la judecată (art. 503 alin. 1). Specială: instanță necompetentă absolut sau complet greșit alcătuit (excepție invocată și nesoluționată); eroare materială; omisiunea de a cerceta un motiv invocat în termen; nepronunțarea asupra unei căi de atac (art. 503 alin. 2–3).'],
      ['Admisibilitatea', 'ÎCCJ, Decizia HP nr. 390/2025: art. 68 L101 nu exclude contestația în anulare specială împotriva hotărârii curții de apel care soluționează plângerea.'],
      ['Procedura', 'Întâmpinarea este obligatorie, cu cel puțin 5 zile înaintea primului termen. Aceeași parte nu poate formula o a doua contestație în anulare împotriva aceleiași hotărâri. Executarea se suspendă numai cu cauțiune (art. 507).'],
    ],
    calc: { zile: [15], de: 'Data comunicării hotărârii' },
    ref: ['II.5.1'], art: 'art. 503–508 C.pr.civ.',
  },
  {
    id: 'x_rev', type: 'remediu', lvl: 3, tr: 'cnsc', col: 17.4, dz: 3.4, roles: ALL,
    t: 'Revizuire', s: 'Revizuire',
    sum: 'Se judecă de instanța care a pronunțat hotărârea atacată; pentru hotărâri definitive potrivnice, de instanța ierarhic superioară celei care a pronunțat prima hotărâre (art. 510 C.pr.civ.).',
    f: [
      ['De drept comun', 'Termen de o lună, calculat diferit pentru fiecare motiv (art. 511). Motive limitative (art. 509 alin. 1): minus sau plus petita, înscrisuri noi reținute de partea adversă, hotărâri definitive potrivnice, o decizie ulterioară a Curții Constituționale etc.'],
      ['Încălcarea dreptului UE', 'O lună de la comunicarea hotărârii definitive; se judecă de urgență și cu precădere (art. 21 Legea 554/2004). Se aplică și hotărârilor care nu evocă fondul. Practica este neunitară privind condițiile de admisibilitate.'],
      ['Procedura', 'Întâmpinarea este obligatorie, cu cel puțin 5 zile înaintea primului termen. Executarea se suspendă numai cu cauțiune (art. 512).'],
    ],
    ref: ['II.5.2'], art: 'art. 509–513 C.pr.civ.; art. 21 L554/2004',
  },
  {
    id: 'r_x', type: 'risc', lvl: 3, tr: 'cnsc', col: 18.4, dz: 0, roles: ALL,
    t: 'Căile extraordinare nu blochează semnarea', s: 'Nu blochează semnarea',
    sum: 'Nu suspendă de drept executarea hotărârii și nu blochează încheierea contractului. Instanța poate suspenda executarea numai sub condiția constituirii unei cauțiuni (art. 507 și 512 C.pr.civ.).',
    ref: ['II.5'], art: 'art. 507, 512 C.pr.civ.',
  },

  // ───────── Calea judiciară (pista din spate)
  {
    id: 't_cont', type: 'remediu', lvl: 1, tr: 'jud', col: 4.6, roles: ['ofertant'],
    t: 'Contestație la tribunal', s: 'Contestație · tribunal',
    sum: 'Calea judiciară, alternativă la CNSC. Ghidul nu o folosește: diferența de cost este decisivă și calea judiciară nu aduce, de regulă, un avantaj care să justifice riscul.',
    f: [
      ['Termenul', '10 zile peste prag și 7 zile sub prag (art. 49).'],
      ['Costul', 'Taxă judiciară de timbru de 2% din valoarea estimată, max. 100.000.000 lei; fără cauțiune. Taxa se recuperează doar dacă operatorul câștigă. La o valoare estimată de 700.000.000 lei, taxa ar fi 14.000.000 lei.'],
      ['Procedura', 'Judiciară, cu citarea părților; soluționare în max. 45 de zile de la sesizare.'],
    ],
    calc: { zile: [10, 7], de: 'Data luării la cunoștință a actului' },
    ref: ['II.1.2'], art: 'art. 49 L101',
  },
  {
    id: 't_sent', type: 'moment', lvl: 1, tr: 'jud', col: 10.2, roles: ALL,
    t: 'Sentința tribunalului', s: 'Sentința',
    sum: 'Pronunțată în max. 45 de zile de la sesizare. După o sentință de menținere, AC trebuie să semneze după termenul de așteptare, chiar dacă se declară recurs (art. 49 alin. 6).',
    ref: ['II.1.2', 'II.7.2'], art: 'art. 49 L101',
  },
  {
    id: 't_recurs', type: 'remediu', lvl: 2, tr: 'jud', col: 12.8, roles: ALL,
    t: 'Recurs la curtea de apel', s: 'Recurs',
    sum: 'Se declară în 10 zile (art. 51). Se aplică, în completare, regulile recursului din C.pr.civ.',
    calc: { zile: [10], de: 'Data comunicării sentinței' },
    ref: ['II.1.2'], art: 'art. 51 L101',
  },
  {
    id: 't_def', type: 'moment', lvl: 2, tr: 'jud', col: 16.9, roles: ALL,
    t: 'Decizie definitivă în recurs', s: 'Decizie definitivă',
    sum: 'Hotărârea curții de apel asupra recursului este definitivă (art. 51 alin. 6) și poate fi atacată numai cu contestație în anulare sau cu revizuire.',
    ref: ['II.5'], art: 'art. 51 alin. 6 L101',
  },
];

// kind: flow (urmează) · choice (alegere) · risk (capcană) · loop (revenire) · out (Partea III)
export const EDGES = [
  ['p_anunt', 'd_doc', 'Analizezi documentația', 'flow'],
  ['d_doc', 'c_doc', 'Da, contest la CNSC', 'choice'],
  ['d_doc', 't_cont', 'Da, contest la tribunal', 'choice'],
  ['d_doc', 'p_depunere', 'Nu, depun ofertă', 'choice'],
  ['d_doc', 'r_tardiv', 'Nu contest acum, dar critic la rezultat', 'risk'],
  ['c_doc', 'c_susp', 'Cer și suspendarea procedurii', 'choice'],
  ['c_doc', 'c_ac', 'AC primește contestația', 'flow'],
  ['c_doc', 'i_interv', 'Alți operatori pot interveni', 'flow'],
  ['c_doc', 'r_caut', 'Nu constitui cauțiunea în 5 zile', 'risk'],
  ['c_doc', 'r_lipsuri', 'Nu completez lipsurile în 3 zile', 'risk'],
  ['c_doc', 'r_dubla', 'Atac același act și la tribunal', 'risk'],
  ['p_depunere', 'p_eval', 'Comisia evaluează ofertele', 'flow'],
  ['p_eval', 'c_rez', 'Atac un act intermediar (ex. clarificări)', 'choice'],
  ['p_eval', 'p_rezultat', 'Se finalizează evaluarea', 'flow'],
  ['p_rezultat', 'a_acces', 'Cer acces la dosar', 'choice'],
  ['p_rezultat', 'd_rez', 'Oferta mea nu a câștigat', 'flow'],
  ['p_rezultat', 'd_castig', 'Oferta mea a câștigat', 'flow'],
  ['p_rezultat', 'k_asteptare', 'Începe termenul de așteptare', 'flow'],
  ['a_acces', 'd_rez', 'Analizez ofertele concurenților', 'flow'],
  ['d_rez', 'c_rez', 'Da, contest la CNSC', 'choice'],
  ['d_rez', 't_cont', 'Da, contest la tribunal', 'choice'],
  ['d_rez', 'k_liber', 'Nu contest', 'choice'],
  ['d_castig', 'i_interv', 'Intervin în contestația concurentului', 'choice'],
  ['d_castig', 'r_interv', 'Ratez termenul de intervenție', 'risk'],
  ['c_rez', 'c_ac', 'AC primește contestația', 'flow'],
  ['c_rez', 'i_interv', 'Contestația se publică în SEAP', 'flow'],
  ['c_rez', 'c_susp', 'Cer suspendarea', 'choice'],
  ['c_rez', 'k_blocaj', 'Semnarea se blochează', 'flow'],
  ['c_rez', 'r_caut', 'Nu constitui cauțiunea în 5 zile', 'risk'],
  ['c_rez', 'r_lipsuri', 'Nu completez lipsurile în 3 zile', 'risk'],
  ['c_rez', 'r_dubla', 'Atac același act și la tribunal', 'risk'],
  ['k_asteptare', 'k_f1', 'AC semnează mai devreme', 'risk'],
  ['k_asteptare', 'k_liber', 'Nu s-a depus contestație', 'flow'],
  ['k_asteptare', 'k_blocaj', 'S-a depus contestație', 'flow'],
  ['k_blocaj', 'k_null', 'AC semnează totuși', 'risk'],
  ['k_blocaj', 'c_dec', 'Blocajul ține până la primirea deciziei', 'flow'],
  ['k_liber', 'k_semnat', 'AC semnează', 'flow'],
  ['c_ac', 'd_remediere', 'AC adoptă măsuri de remediere', 'flow'],
  ['c_ac', 'c_proc', 'AC trimite punctul de vedere', 'flow'],
  ['d_remediere', 's_renunt', 'Da, renunț la contestație', 'choice'],
  ['d_remediere', 'c_proc', 'Nu, continui', 'choice'],
  ['c_susp', 'c_proc', 'CNSC decide prin încheiere în 3 zile', 'flow'],
  ['i_interv', 'c_proc', 'Devin parte în procedură', 'flow'],
  ['c_proc', 'c_dec', 'CNSC se pronunță', 'flow'],
  ['c_dec', 's_exc', 'Excepție întemeiată', 'flow'],
  ['c_dec', 's_nef', 'Act legal și temeinic', 'flow'],
  ['c_dec', 's_anul', 'Act nelegal, remediabil', 'flow'],
  ['c_dec', 's_anproc', 'Remedierea nu e posibilă', 'flow'],
  ['s_exc', 'k_obligatie', 'Rezultatul rămâne în picioare', 'flow'],
  ['s_nef', 'k_obligatie', 'Rezultatul rămâne în picioare', 'flow'],
  ['s_exc', 'd_pl', 'Contestatorul poate ataca', 'flow'],
  ['s_nef', 'd_pl', 'Contestatorul poate ataca', 'flow'],
  ['s_anul', 'd_pl', 'AC sau câștigătorul pot ataca', 'flow'],
  ['s_anul', 'a_exec', 'AC trebuie să execute decizia', 'flow'],
  ['s_anproc', 'd_pl', 'AC sau câștigătorul pot ataca', 'flow'],
  ['s_anproc', 'p3', 'Litigii după anularea procedurii', 'out'],
  ['d_pl', 'pl', 'Da, plângere în 10 zile', 'choice'],
  ['d_pl', 'k_obligatie', 'Nimeni nu atacă menținerea', 'choice'],
  ['d_pl', 'a_exec', 'Nimeni nu atacă admiterea', 'choice'],
  ['a_exec', 'p_depunere', 'Documentația a fost modificată', 'loop'],
  ['a_exec', 'k_noua', 'Ofertele au fost reevaluate', 'flow'],
  ['k_noua', 'p_rezultat', 'Un nou ciclu de contestare', 'loop'],
  ['pl', 'r_pl', 'Nu comunic plângerea părților în 10 zile', 'risk'],
  ['pl', 'pl_susp', 'Cer suspendarea procedurii sau a contractului', 'choice'],
  ['pl', 'pl_proc', 'Se fixează primul termen', 'flow'],
  ['pl_susp', 'pl_proc', 'Încheiere definitivă', 'flow'],
  ['pl_proc', 'pl_mod', 'Plângere întemeiată', 'flow'],
  ['pl_proc', 'pl_rejud', 'CNSC nu a analizat fondul integral', 'flow'],
  ['pl_proc', 'pl_resp', 'Plângere neîntemeiată', 'flow'],
  ['pl_rejud', 'pl_mod', 'După rejudecarea fondului', 'flow'],
  ['pl_rejud', 'pl_resp', 'După rejudecarea fondului', 'flow'],
  ['pl_mod', 'a_exec', 'AC execută hotărârea', 'flow'],
  ['pl_mod', 'pl_def', 'Hotărârea e definitivă', 'flow'],
  ['pl_resp', 'pl_def', 'Hotărârea e definitivă', 'flow'],
  ['pl_def', 'x_ca', 'Contestație în anulare', 'choice'],
  ['pl_def', 'x_rev', 'Revizuire', 'choice'],
  ['pl_def', 'k_schimbare', 'Contractul fusese deja semnat', 'flow'],
  ['x_ca', 'r_x', 'Sper că se blochează semnarea', 'risk'],
  ['x_rev', 'r_x', 'Sper că se blochează semnarea', 'risk'],
  ['k_obligatie', 'k_semnat', 'AC semnează', 'flow'],
  ['k_obligatie', 'pl_susp', 'Contestatorul vrea să blocheze semnarea', 'choice'],
  ['k_semnat', 'k_schimbare', 'Calea de atac schimbă soluția', 'flow'],
  ['k_semnat', 'p3', 'Executare, nulitate, despăgubiri', 'out'],
  ['k_schimbare', 'k_nul', 'Semnat înainte de decizia CNSC', 'flow'],
  ['k_schimbare', 'k_desp', 'Semnat corect, după menținere', 'flow'],
  ['k_nul', 'p3', 'Acțiunea în nulitate (III.2)', 'out'],
  ['k_desp', 'p3', 'Acțiunea în despăgubiri (III.3)', 'out'],
  ['k_null', 'p3', 'Acțiunea în nulitate (III.2)', 'out'],
  ['t_cont', 't_sent', 'Tribunalul judecă în max. 45 de zile', 'flow'],
  ['t_cont', 'k_blocaj', 'Semnarea se blochează', 'flow'],
  ['t_cont', 'r_dubla', 'Atac același act și la CNSC', 'risk'],
  ['t_sent', 'k_obligatie', 'Menținere', 'flow'],
  ['t_sent', 'a_exec', 'Admitere', 'flow'],
  ['t_sent', 't_recurs', 'Recurs în 10 zile', 'choice'],
  ['t_recurs', 't_def', 'Curtea de apel se pronunță', 'flow'],
  ['t_def', 'x_ca', 'Contestație în anulare', 'choice'],
  ['t_def', 'x_rev', 'Revizuire', 'choice'],
  ['t_def', 'k_schimbare', 'Contractul fusese deja semnat', 'flow'],
];

export const PATHS = [
  { id: 'doc', name: 'Atac documentația', nodes: ['p_anunt', 'd_doc', 'c_doc', 'c_susp', 'c_proc', 'c_dec', 's_anul', 'a_exec', 'p_depunere'] },
  { id: 'rez', name: 'Pierd și atac rezultatul', nodes: ['p_rezultat', 'a_acces', 'd_rez', 'c_rez', 'c_ac', 'c_proc', 'c_dec', 's_nef', 'd_pl', 'pl', 'pl_susp', 'pl_proc', 'pl_mod', 'a_exec', 'k_noua'] },
  { id: 'cast', name: 'Câștig și apăr rezultatul', nodes: ['p_rezultat', 'd_castig', 'i_interv', 'c_proc', 'c_dec', 's_anul', 'd_pl', 'pl', 'pl_proc', 'pl_resp', 'pl_def'] },
  { id: 'contr', name: 'Când se poate semna contractul', nodes: ['p_rezultat', 'k_asteptare', 'k_blocaj', 'c_dec', 's_nef', 'k_obligatie', 'k_semnat', 'k_schimbare', 'k_desp', 'p3'] },
  { id: 'jud', name: 'Calea judiciară', nodes: ['d_rez', 't_cont', 't_sent', 't_recurs', 't_def', 'x_rev'] },
];

// Sărbători legale (RO), pentru calculatorul de termene
export const HOLIDAYS = [
  '2026-01-01', '2026-01-02', '2026-01-06', '2026-01-07', '2026-01-24', '2026-04-10', '2026-04-12', '2026-04-13',
  '2026-05-01', '2026-05-31', '2026-06-01', '2026-08-15', '2026-11-30', '2026-12-01', '2026-12-25', '2026-12-26',
  '2027-01-01', '2027-01-02', '2027-01-06', '2027-01-07', '2027-01-24', '2027-04-30', '2027-05-01', '2027-05-02',
  '2027-05-03', '2027-06-01', '2027-06-20', '2027-06-21', '2027-08-15', '2027-11-30', '2027-12-01', '2027-12-25', '2027-12-26',
];
